# Generated by Django 3.1 on 2019-10-24 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NAP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='description',
            new_name='Meeting_Description',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='title',
            new_name='Meeting_Name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='completed',
        ),
        migrations.AddField(
            model_name='upload',
            name='Meeting_Audio_File',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='Meeting_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
